apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "payment-api.fullname" . }}
  labels:
    {{- include "payment-api.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "payment-api.selectorLabels" . | nindent 6 }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        app: payment-api
        {{- include "payment-api.selectorLabels" . | nindent 8 }}

    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      containers:
        - name: payment-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          env:
            - name: SERVICE_NAME
              value: {{ .Values.env.SERVICE_NAME | quote }}

            - name: ENVIRONMENT
              value: {{ .Values.env.ENVIRONMENT | quote }}

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
